### ISSUE TITLE
Add new workflow for patching main package

### ISSUE THREAD

**Issue by nandordudas** [nandordudas/monorepo-starter#3]
### Clear and concise description

Create GitHub action which runs after any pull request has been closed and bumps up patch version of the main package.

### Additional context

How to control minor or major version bumps?

I hope it is a good idea to create a new pull request which contains version bumps. The main package will never be published so it's version is just an index.

🤔

**Comment by nandordudas** [comment]
Here is the possible workflow but it depends on some permissions and code review approvals.

The solution is not trivial, so the issue has been closed temporary.

```yaml
name: Patch

permissions:
  pull-requests: write

on:
  pull_request:
    types:
      - closed
jobs:
  patch:
    if: github.event.pull_request.merged == true
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version-file: package.json
      - name: 🦜 Bump up version
        run: |
          git config --global user.name "Release Parrot"
          git config --global user.email release.parrot@bump.patch
          npx bumpp patch --yes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```
